// mobile/src/constants/permissions.ts

export const PERMISSIONS_MAP: Record<string, string[]> = {
  admin: [
    // Users
    'USERS:READ', 'USERS:CREATE', 'USERS:UPDATE', 'USERS:DELETE',
    // Exploitations
    'EXPLOITATIONS:READ', 'EXPLOITATIONS:CREATE', 'EXPLOITATIONS:UPDATE',
    'EXPLOITATIONS:DELETE', 'EXPLOITATIONS:EXPORT', 'EXPLOITATIONS:AGGREGATE',
    // Herd
    'HERD:READ', 'HERD:CREATE', 'HERD:UPDATE', 'HERD:DELETE',
    'HERD:VALIDATE', 'HERD:EXPORT', 'HERD:AGGREGATE',
    // Health (old + granular)
    'HEALTH:READ', 'HEALTH:CREATE', 'HEALTH:UPDATE', 'HEALTH:DELETE',
    'HEALTH_RECORD:READ', 'HEALTH_RECORD:CREATE', 'HEALTH_RECORD:UPDATE', 'HEALTH_RECORD:DELETE',
    'TREATMENT:READ', 'TREATMENT:CREATE', 'TREATMENT:UPDATE', 'TREATMENT:DELETE', 'TREATMENT:ADMINISTER',
    'VACCINATION:READ', 'VACCINATION:CREATE', 'VACCINATION:UPDATE', 'VACCINATION:DELETE',
    'INTERVENTION:READ', 'INTERVENTION:CREATE', 'INTERVENTION:UPDATE', 'INTERVENTION:DELETE',
    'HEALTH_REPORT:READ',
    // Reproduction
    'REPRODUCTION:READ', 'REPRODUCTION:CREATE', 'REPRODUCTION:UPDATE',
    'REPRODUCTION:DELETE', 'REPRODUCTION:EXPORT', 'REPRODUCTION:AGGREGATE',
    // IoT
    'IOT:SHIELDS:READ', 'IOT:SHIELDS:CREATE', 'IOT:SHIELDS:UPDATE', 'IOT:SHIELDS:DELETE',
    'IOT:SENSOR:READ', 'IOT:SENSOR:CREATE',
    'IOT:ALERTS:READ', 'IOT:ALERTS:CREATE', 'IOT:ALERTS:UPDATE', 'IOT:ALERTS:DELETE',
    'IOT:ZONES:READ', 'IOT:ZONES:CREATE', 'IOT:ZONES:UPDATE', 'IOT:ZONES:DELETE',
    'IOT:ANALYTICS:READ',
    // 🟢 FINANCE – full CRUD
    'FINANCE:BUDGET:READ', 'FINANCE:BUDGET:CREATE', 'FINANCE:BUDGET:UPDATE', 'FINANCE:BUDGET:DELETE',
    'FINANCE:EXPENSE:READ', 'FINANCE:EXPENSE:CREATE', 'FINANCE:EXPENSE:UPDATE', 'FINANCE:EXPENSE:DELETE',
    'FINANCE:REVENUE:READ', 'FINANCE:REVENUE:CREATE', 'FINANCE:REVENUE:UPDATE', 'FINANCE:REVENUE:DELETE',
    'FINANCE:CASHFLOW:READ', 'FINANCE:CASHFLOW:CREATE', 'FINANCE:CASHFLOW:UPDATE', 'FINANCE:CASHFLOW:DELETE',
    'FINANCE:PROFITABILITY:READ', 'FINANCE:PROFITABILITY:CREATE', 'FINANCE:PROFITABILITY:UPDATE', 'FINANCE:PROFITABILITY:DELETE',
    'FINANCE:REPORT:READ', 'FINANCE:REPORT:CREATE', 'FINANCE:REPORT:UPDATE', 'FINANCE:REPORT:DELETE',
    'FINANCE:COST:READ', 'FINANCE:COST:CREATE', 'FINANCE:COST:UPDATE', 'FINANCE:COST:DELETE',
  ],
  manager: [
    'EXPLOITATIONS:READ', 'EXPLOITATIONS:UPDATE', 'EXPLOITATIONS:EXPORT',
    'HERD:READ', 'HERD:VALIDATE', 'HERD:EXPORT',
    'HEALTH:READ',
    'HEALTH_RECORD:READ',
    'TREATMENT:READ',
    'VACCINATION:READ',
    'INTERVENTION:READ',
    'HEALTH_REPORT:READ',
    'REPRODUCTION:READ', 'REPRODUCTION:EXPORT',
    'IOT:SHIELDS:READ',
    'IOT:SENSOR:READ',
    'IOT:ALERTS:READ',
    'IOT:ZONES:READ',
    'IOT:ANALYTICS:READ',
    // 🟢 FINANCE – full CRUD for manager
    'FINANCE:BUDGET:READ', 'FINANCE:BUDGET:CREATE', 'FINANCE:BUDGET:UPDATE', 'FINANCE:BUDGET:DELETE',
    'FINANCE:EXPENSE:READ', 'FINANCE:EXPENSE:CREATE', 'FINANCE:EXPENSE:UPDATE', 'FINANCE:EXPENSE:DELETE',
    'FINANCE:REVENUE:READ', 'FINANCE:REVENUE:CREATE', 'FINANCE:REVENUE:UPDATE', 'FINANCE:REVENUE:DELETE',
    'FINANCE:CASHFLOW:READ', 'FINANCE:CASHFLOW:CREATE', 'FINANCE:CASHFLOW:UPDATE', 'FINANCE:CASHFLOW:DELETE',
    'FINANCE:PROFITABILITY:READ', 'FINANCE:PROFITABILITY:CREATE', 'FINANCE:PROFITABILITY:UPDATE', 'FINANCE:PROFITABILITY:DELETE',
    'FINANCE:REPORT:READ', 'FINANCE:REPORT:CREATE', 'FINANCE:REPORT:UPDATE', 'FINANCE:REPORT:DELETE',
    'FINANCE:COST:READ', 'FINANCE:COST:CREATE', 'FINANCE:COST:UPDATE', 'FINANCE:COST:DELETE',
  ],
  eleveur: [
    'EXPLOITATIONS:READ', 'EXPLOITATIONS:UPDATE',
    'HERD:READ', 'HERD:CREATE', 'HERD:UPDATE', 'HERD:DELETE',
    'HEALTH:READ',
    'HEALTH_RECORD:READ',
    'TREATMENT:READ',
    'VACCINATION:READ', 'VACCINATION:CREATE', 'VACCINATION:UPDATE', 'VACCINATION:DELETE',
    'INTERVENTION:READ',
    'REPRODUCTION:READ', 'REPRODUCTION:CREATE', 'REPRODUCTION:UPDATE', 'REPRODUCTION:DELETE',
    'IOT:SHIELDS:READ', 'IOT:SHIELDS:CREATE', 'IOT:SHIELDS:UPDATE', 'IOT:SHIELDS:DELETE',
    'IOT:SENSOR:READ', 'IOT:SENSOR:CREATE',
    'IOT:ALERTS:READ', 'IOT:ALERTS:CREATE', 'IOT:ALERTS:UPDATE', 'IOT:ALERTS:DELETE',
    'IOT:ZONES:READ', 'IOT:ZONES:CREATE', 'IOT:ZONES:UPDATE', 'IOT:ZONES:DELETE',
    'IOT:ANALYTICS:READ',
    // 🟢 FINANCE – read only
    'FINANCE:BUDGET:READ',
    'FINANCE:EXPENSE:READ',
    'FINANCE:REVENUE:READ',
    'FINANCE:CASHFLOW:READ',
    'FINANCE:PROFITABILITY:READ',
    'FINANCE:REPORT:READ',
  ],
  ouvrier: [
    'EXPLOITATIONS:READ',
    'HERD:READ',
    'HEALTH_RECORD:READ',
    'TREATMENT:READ',
    'VACCINATION:READ',
    'INTERVENTION:READ',
    // ❌ No finance permissions
  ],
  veterinaire: [
    'EXPLOITATIONS:READ',
    'HERD:READ', 'HERD:UPDATE',
    'HEALTH:READ', 'HEALTH:CREATE', 'HEALTH:UPDATE', 'HEALTH:DELETE',
    'HEALTH_RECORD:READ', 'HEALTH_RECORD:CREATE', 'HEALTH_RECORD:UPDATE', 'HEALTH_RECORD:DELETE',
    'TREATMENT:READ', 'TREATMENT:CREATE', 'TREATMENT:UPDATE', 'TREATMENT:DELETE', 'TREATMENT:ADMINISTER',
    'VACCINATION:READ',
    'INTERVENTION:READ', 'INTERVENTION:CREATE', 'INTERVENTION:UPDATE', 'INTERVENTION:DELETE',
    'HEALTH_REPORT:READ',
    'IOT:SHIELDS:READ',
    'IOT:SENSOR:READ',
    'IOT:ALERTS:READ',
    'IOT:ANALYTICS:READ',
    // 🟢 FINANCE – read only on expenses and reports
    'FINANCE:EXPENSE:READ',
    'FINANCE:REPORT:READ',
  ],
  cooperative: [
    'EXPLOITATIONS:READ', 'EXPLOITATIONS:AGGREGATE',
    'HERD:READ', 'HERD:AGGREGATE',
    'HEALTH_RECORD:READ',
    'TREATMENT:READ',
    'VACCINATION:READ',
    'INTERVENTION:READ',
    'HEALTH_REPORT:READ',
    // 🟢 FINANCE – read only aggregated reports
    'FINANCE:REPORT:READ',
  ],
};

export function hasPermission(roleName: string, module: string, action: string): boolean {
  const normalizedRole = roleName.toLowerCase();
  const perms = PERMISSIONS_MAP[normalizedRole] || [];
  return perms.includes(`${module}:${action}`);
}

export function canAccessModule(roleName: string, module: string): boolean {
  const normalizedRole = roleName.toLowerCase();
  const perms = PERMISSIONS_MAP[normalizedRole] || [];
  return perms.some(p => p.startsWith(`${module}:`));
}