import { useCallback, useEffect, useState } from "react";
import { Alert, Pressable, ScrollView, StyleSheet, Switch, Text, TextInput, View } from "react-native";
import { Picker } from "@react-native-picker/picker";
import { router } from "expo-router";
import { BiAlertChannel, BiAlertRule, BiAlertRuleType, listBiAlertRules, saveBiAlertRules } from "@/services/biAlertRulesService";
const channels: BiAlertChannel[] = ["inApp", "email", "sms"];
const labels: Record<BiAlertChannel,string> = { inApp:"Dans l’app", email:"E-mail", sms:"SMS" };
export default function BiAlertRulesScreen(){ const [rules,setRules]=useState<BiAlertRule[]>([]); useEffect(()=>{void listBiAlertRules().then(setRules);},[]); const save=useCallback(async(next:BiAlertRule[])=>{setRules(next);await saveBiAlertRules(next);},[]); const add=()=>save([...rules,{id:Date.now().toString(),metric:"mortality",type:"fixed",threshold:5,periodDays:30,severity:"WARNING",channels:["inApp"],enabled:true}]); const update=(id:string,patch:Partial<BiAlertRule>)=>save(rules.map(r=>r.id===id?{...r,...patch}:r)); const remove=(id:string)=>save(rules.filter(r=>r.id!==id)); return <ScrollView style={s.page} contentContainerStyle={s.content}><View style={s.head}><Pressable onPress={()=>router.back()}><Text style={s.back}>‹</Text></Pressable><View><Text style={s.title}>Seuils d’alerte</Text><Text style={s.sub}>Définissez vos critères et canaux de notification.</Text></View></View>{rules.map(rule=><View key={rule.id} style={s.card}><View style={s.row}><Text style={s.cardTitle}>Règle d’indicateur</Text><Switch value={rule.enabled} onValueChange={enabled=>update(rule.id,{enabled})}/></View><Picker selectedValue={rule.metric} onValueChange={metric=>update(rule.id,{metric:metric as BiAlertRule["metric"]})}><Picker.Item label="Mortalité (%)" value="mortality"/><Picker.Item label="Fertilité (%)" value="fertility"/><Picker.Item label="GMQ (g/j)" value="gmq"/><Picker.Item label="Marge nette" value="netMargin"/></Picker><Picker selectedValue={rule.type} onValueChange={type=>update(rule.id,{type:type as BiAlertRuleType})}><Picker.Item label="Valeur fixe" value="fixed"/><Picker.Item label="Écart par rapport à la moyenne" value="averageDeviation"/><Picker.Item label="Tendance / variation" value="trend"/></Picker><View style={s.row}><TextInput style={s.input} keyboardType="numeric" value={String(rule.threshold)} onChangeText={v=>update(rule.id,{threshold:Number(v)||0})} placeholder="Seuil"/><TextInput style={s.input} keyboardType="numeric" value={String(rule.periodDays)} onChangeText={v=>update(rule.id,{periodDays:Number(v)||1})} placeholder="Jours"/></View><Text style={s.label}>Criticité</Text><View style={s.chips}>{(["INFO","WARNING","CRITICAL"] as const).map(x=><Pressable key={x} onPress={()=>update(rule.id,{severity:x})} style={[s.chip,rule.severity===x&&s.active]}><Text style={rule.severity===x?s.activeText:undefined}>{x}</Text></Pressable>)}</View><Text style={s.label}>Notifications</Text><View style={s.chips}>{channels.map(x=><Pressable key={x} onPress={()=>update(rule.id,{channels:rule.channels.includes(x)?rule.channels.filter(c=>c!==x):[...rule.channels,x]})} style={[s.chip,rule.channels.includes(x)&&s.active]}><Text style={rule.channels.includes(x)?s.activeText:undefined}>{labels[x]}</Text></Pressable>)}</View><Pressable onPress={()=>remove(rule.id)}><Text style={s.delete}>Supprimer la règle</Text></Pressable></View>)}<Pressable style={s.add} onPress={add}><Text style={s.addText}>+ Ajouter un seuil</Text></Pressable></ScrollView>; }
const s=StyleSheet.create({page:{flex:1,backgroundColor:"#F5F7F5"},content:{padding:16,gap:12},head:{flexDirection:"row",gap:12,alignItems:"center",marginBottom:8},back:{fontSize:34,color:"#2E7D32"},title:{fontSize:22,fontWeight:"700"},sub:{color:"#6B6B6B"},card:{backgroundColor:"#fff",borderRadius:14,padding:14,gap:8},row:{flexDirection:"row",justifyContent:"space-between",gap:10,alignItems:"center"},cardTitle:{fontWeight:"700",fontSize:16},input:{flex:1,borderWidth:1,borderColor:"#DDE5DE",borderRadius:9,padding:11},label:{fontSize:12,color:"#6B6B6B",marginTop:5},chips:{flexDirection:"row",gap:7,flexWrap:"wrap"},chip:{borderWidth:1,borderColor:"#CFE0D0",paddingHorizontal:10,paddingVertical:7,borderRadius:18},active:{backgroundColor:"#2E7D32",borderColor:"#2E7D32"},activeText:{color:"#fff",fontWeight:"700"},delete:{color:"#C62828",fontWeight:"600",marginTop:6},add:{backgroundColor:"#2E7D32",padding:15,borderRadius:12,alignItems:"center"},addText:{color:"#fff",fontWeight:"700"}});
