import { useMemo, useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { router } from "expo-router";
const vars=["Alimentation","GMQ","Santé","Fertilité","BCS","Coût/kg"];
const matrix=[[1,.72,.18,.31,.48,-.41],[.72,1,.12,.36,.62,-.53],[.18,.12,1,.58,.34,-.22],[.31,.36,.58,1,.39,-.27],[.48,.62,.34,.39,1,-.45],[-.41,-.53,-.22,-.27,-.45,1]];
const points=Array.from({length:18},(_,i)=>({x:1.2+i*.12,y:95+i*8+(i%4)*14}));
export default function Correlations(){const [mode,setMode]=useState<"matrix"|"scatter">("matrix");const strongest=useMemo(()=>({label:"Alimentation ↔ GMQ",value:.72}),[]);return <ScrollView style={s.p} contentContainerStyle={s.c}><View style={s.h}><Pressable onPress={()=>router.back()}><Text style={s.back}>‹</Text></Pressable><View><Text style={s.t}>Corrélations</Text><Text style={s.sub}>Identifiez les leviers de performance inter-modules.</Text></View></View><View style={s.tabs}><Pressable onPress={()=>setMode("matrix")} style={[s.tab,mode==="matrix"&&s.on]}><Text style={mode==="matrix"&&s.onText}>Matrice / heatmap</Text></Pressable><Pressable onPress={()=>setMode("scatter")} style={[s.tab,mode==="scatter"&&s.on]}><Text style={mode==="scatter"&&s.onText}>Nuage & régression</Text></Pressable></View>{mode==="matrix"?<><View style={s.insight}><Text style={s.insightTitle}>Relation la plus forte</Text><Text style={s.insightValue}>{strongest.label} · r = {strongest.value}</Text><Text style={s.sub}>Une valeur proche de 1 ou -1 indique une relation plus marquée.</Text></View><ScrollView horizontal><View><View style={s.row}><View style={s.corner}/>{vars.map(x=><Text key={x} style={s.axis}>{x.slice(0,5)}</Text>)}</View>{matrix.map((row,i)=><View style={s.row} key={vars[i]}><Text style={s.yaxis}>{vars[i].slice(0,8)}</Text>{row.map((value,j)=><View key={j} style={[s.cell,{backgroundColor:color(value)}]}><Text style={s.cellText}>{value.toFixed(2)}</Text></View>)}</View>)}</View></ScrollView><View style={s.legend}><Text>−1 négative</Text><View style={s.legendBar}/><Text>positive +1</Text></View></>:<><Text style={s.section}>Alimentation quotidienne vs GMQ</Text><Text style={s.sub}>Chaque point représente une observation de lot. La ligne indique la régression linéaire.</Text><View style={s.chart}><View style={s.line}/>{points.map((p,i)=><View key={i} style={[s.dot,{left:`${((p.x-1.1)/2.3)*100}%`,bottom:`${((p.y-80)/190)*100}%`} ]}/>)}</View><View style={s.chartLabels}><Text>1,2 kg/j</Text><Text>GMQ (g/j) · r = 0,72</Text><Text>3,5 kg/j</Text></View><View style={s.insight}><Text style={s.insightTitle}>Interprétation</Text><Text style={s.sub}>Une hausse de l’alimentation est associée à une hausse du GMQ. Cette relation ne prouve pas une causalité : vérifiez santé, âge et race avant décision.</Text></View></>}</ScrollView>}
function color(v:number){const a=Math.round(45+Math.abs(v)*150);return v>=0?`rgb(${230-a},${250-a/3},${235-a/2})`:`rgb(250,${235-a/2},${235-a/3})`};
const s=StyleSheet.create({p:{flex:1,backgroundColor:"#F5F7F5"},c:{padding:16,gap:14},h:{flexDirection:"row",gap:12,alignItems:"center"},back:{fontSize:34,color:"#2E7D32"},t:{fontSize:22,fontWeight:"700"},sub:{fontSize:12,color:"#6B6B6B",lineHeight:18},tabs:{flexDirection:"row",gap:8},tab:{padding:10,borderRadius:18,borderWidth:1,borderColor:"#CFE0D0"},on:{backgroundColor:"#2E7D32",borderColor:"#2E7D32"},onText:{color:"#fff",fontWeight:"700"},insight:{backgroundColor:"#fff",padding:14,borderRadius:13,gap:5},insightTitle:{color:"#2E7D32",fontWeight:"700"},insightValue:{fontSize:16,fontWeight:"700"},row:{flexDirection:"row"},corner:{width:75,height:34},axis:{width:58,fontSize:10,color:"#6B6B6B",textAlign:"center",height:34},yaxis:{width:75,fontSize:10,color:"#6B6B6B",paddingTop:17},cell:{width:58,height:52,alignItems:"center",justifyContent:"center",borderWidth:.5,borderColor:"#fff"},cellText:{fontSize:10,fontWeight:"700",color:"#18321D"},legend:{flexDirection:"row",alignItems:"center",justifyContent:"center",gap:8,fontSize:11,color:"#6B6B6B"},legendBar:{width:80,height:9,borderRadius:5,backgroundColor:"#7DC783"},section:{fontSize:17,fontWeight:"700",marginTop:5},chart:{height:300,backgroundColor:"#fff",borderRadius:14,marginTop:10,overflow:"hidden",borderLeftWidth:2,borderBottomWidth:2,borderColor:"#A8B8AA",position:"relative"},dot:{position:"absolute",width:11,height:11,borderRadius:6,backgroundColor:"#2E7D32",opacity:.8},line:{position:"absolute",width:"115%",height:3,backgroundColor:"#C62828",transform:[{rotate:"-29deg"}],top:145,left:-25},chartLabels:{flexDirection:"row",justifyContent:"space-between",fontSize:11,color:"#6B6B6B"}});
