import type { Context } from "hono";
import { and, desc, eq, gte, inArray, lt } from "drizzle-orm";
import { db } from "../db/connection.js";
import { employees, employmentContracts, workHours, workSchedules } from "../db/schema/index.js";
import { contractSchema, employeeSchema, hoursSchema, scheduleSchema } from "../validators/teams.validator.js";

function bodyError(c: Context, parsed: { success: false; error: { flatten: () => unknown } }) { return c.json({ error: parsed.error.flatten() }, 400); }
function id(c: Context, key = "id") { const value = Number(c.req.param(key)); return Number.isInteger(value) && value > 0 ? value : null; }

export async function listEmployees(c: Context) {
  const exploitationId = Number(c.req.query("exploitationId"));
  if (!Number.isInteger(exploitationId) || exploitationId <= 0) return c.json({ error: "exploitationId invalide." }, 400);
  return c.json({ data: await db.select().from(employees).where(eq(employees.exploitationId, exploitationId)).orderBy(employees.lastName, employees.firstName) });
}
export async function createEmployee(c: Context) { const parsed = employeeSchema.safeParse(await c.req.json()); if (!parsed.success) return bodyError(c, parsed); const [created] = await db.insert(employees).values(parsed.data).$returningId(); return c.json({ data: await db.query.employees.findFirst({ where: eq(employees.id, created.id) }) }, 201); }
export async function updateEmployee(c: Context) { const employeeId = id(c); if (!employeeId) return c.json({ error: "Identifiant invalide." }, 400); const parsed = employeeSchema.partial().omit({ exploitationId: true }).safeParse(await c.req.json()); if (!parsed.success) return bodyError(c, parsed); await db.update(employees).set({ ...parsed.data, updatedAt: new Date() }).where(eq(employees.id, employeeId)); return c.json({ data: await db.query.employees.findFirst({ where: eq(employees.id, employeeId) }) }); }

export async function listContracts(c: Context) { const employeeId = Number(c.req.query("employeeId")); if (!Number.isInteger(employeeId) || employeeId <= 0) return c.json({ error: "employeeId invalide." }, 400); return c.json({ data: await db.select().from(employmentContracts).where(eq(employmentContracts.employeeId, employeeId)).orderBy(desc(employmentContracts.startDate)) }); }
export async function createContract(c: Context) { const parsed = contractSchema.safeParse(await c.req.json()); if (!parsed.success) return bodyError(c, parsed); const [created] = await db.insert(employmentContracts).values({ ...parsed.data, hourlyRate: String(parsed.data.hourlyRate), monthlySalary: parsed.data.monthlySalary === undefined ? undefined : String(parsed.data.monthlySalary) }).$returningId(); return c.json({ data: await db.query.employmentContracts.findFirst({ where: eq(employmentContracts.id, created.id) }) }, 201); }

export async function listSchedules(c: Context) { const exploitationId = Number(c.req.query("exploitationId")); const date = c.req.query("date"); if (!Number.isInteger(exploitationId) || exploitationId <= 0) return c.json({ error: "exploitationId invalide." }, 400); const conditions = [eq(employees.exploitationId, exploitationId)]; if (date) conditions.push(eq(workSchedules.workDate, date)); const data = await db.select({ id: workSchedules.id, employeeId: employees.id, employeeName: employees.firstName, employeeLastName: employees.lastName, workDate: workSchedules.workDate, startTime: workSchedules.startTime, endTime: workSchedules.endTime, task: workSchedules.task, status: workSchedules.status }).from(workSchedules).innerJoin(employees, eq(workSchedules.employeeId, employees.id)).where(and(...conditions)).orderBy(workSchedules.workDate, workSchedules.startTime); return c.json({ data }); }
export async function createSchedule(c: Context) { const parsed = scheduleSchema.safeParse(await c.req.json()); if (!parsed.success) return bodyError(c, parsed); const [created] = await db.insert(workSchedules).values(parsed.data).$returningId(); return c.json({ data: await db.query.workSchedules.findFirst({ where: eq(workSchedules.id, created.id) }) }, 201); }

export async function listHours(c: Context) { const employeeId = Number(c.req.query("employeeId")); if (!Number.isInteger(employeeId) || employeeId <= 0) return c.json({ error: "employeeId invalide." }, 400); return c.json({ data: await db.select().from(workHours).where(eq(workHours.employeeId, employeeId)).orderBy(desc(workHours.workDate)) }); }
export async function createHours(c: Context) { const parsed = hoursSchema.safeParse(await c.req.json()); if (!parsed.success) return bodyError(c, parsed); const [created] = await db.insert(workHours).values({ ...parsed.data, hours: String(parsed.data.hours), overtimeHours: String(parsed.data.overtimeHours) }).$returningId(); return c.json({ data: await db.query.workHours.findFirst({ where: eq(workHours.id, created.id) }) }, 201); }

export async function labourCosts(c: Context) { const exploitationId = Number(c.req.query("exploitationId")); const month = c.req.query("month") ?? new Date().toISOString().slice(0, 7); if (!Number.isInteger(exploitationId) || exploitationId <= 0 || !/^\d{4}-\d{2}$/.test(month)) return c.json({ error: "Paramètres invalides." }, 400); const start = `${month}-01`; const endDate = new Date(`${start}T00:00:00Z`); endDate.setUTCMonth(endDate.getUTCMonth() + 1); const end = endDate.toISOString().slice(0, 10); const staff = await db.select().from(employees).where(eq(employees.exploitationId, exploitationId)); if (!staff.length) return c.json({ data: { month, totalHours: 0, totalCost: 0, employees: [] } }); const ids = staff.map((employee) => employee.id); const [hours, contracts] = await Promise.all([db.select().from(workHours).where(and(inArray(workHours.employeeId, ids), gte(workHours.workDate, start), lt(workHours.workDate, end))), db.select().from(employmentContracts).where(inArray(employmentContracts.employeeId, ids))]); const totals = staff.map((employee) => { const hoursForEmployee = hours.filter((entry) => entry.employeeId === employee.id); const totalHours = hoursForEmployee.reduce((sum, entry) => sum + Number(entry.hours) + Number(entry.overtimeHours), 0); const contract = contracts.filter((entry) => entry.employeeId === employee.id).sort((a, b) => String(b.startDate).localeCompare(String(a.startDate)))[0]; const hourlyRate = Number(contract?.hourlyRate ?? 0); return { employeeId: employee.id, name: `${employee.firstName} ${employee.lastName}`, totalHours, hourlyRate, cost: totalHours * hourlyRate }; }); return c.json({ data: { month, totalHours: totals.reduce((sum, item) => sum + item.totalHours, 0), totalCost: totals.reduce((sum, item) => sum + item.cost, 0), employees: totals } }); }
