// backend/src/constants/permissions.ts

export const PERMISSIONS_MAP: Record<string, string[]> = {
  admin: [
    'USERS:READ', 'USERS:CREATE', 'USERS:UPDATE', 'USERS:DELETE',
    'EXPLOITATIONS:READ', 'EXPLOITATIONS:CREATE', 'EXPLOITATIONS:UPDATE',
    'EXPLOITATIONS:DELETE', 'EXPLOITATIONS:EXPORT', 'EXPLOITATIONS:AGGREGATE',
    'HERD:READ', 'HERD:CREATE', 'HERD:UPDATE', 'HERD:DELETE',
    'HERD:VALIDATE', 'HERD:EXPORT', 'HERD:AGGREGATE',
    // ✅ Old health permissions (full) - for vet/admin only
    'HEALTH:READ', 'HEALTH:CREATE', 'HEALTH:UPDATE', 'HEALTH:DELETE',
    // ✅ New granular permissions
    'HEALTH_RECORD:READ', 'HEALTH_RECORD:CREATE', 'HEALTH_RECORD:UPDATE', 'HEALTH_RECORD:DELETE',
    'TREATMENT:READ', 'TREATMENT:CREATE', 'TREATMENT:UPDATE', 'TREATMENT:DELETE', 'TREATMENT:ADMINISTER',
    'VACCINATION:READ', 'VACCINATION:CREATE', 'VACCINATION:UPDATE', 'VACCINATION:DELETE',
    'INTERVENTION:READ', 'INTERVENTION:CREATE', 'INTERVENTION:UPDATE', 'INTERVENTION:DELETE',
    'HEALTH_REPORT:READ',
    'REPRODUCTION:READ', 'REPRODUCTION:CREATE', 'REPRODUCTION:UPDATE',
    'REPRODUCTION:DELETE', 'REPRODUCTION:EXPORT', 'REPRODUCTION:AGGREGATE',
    'IOT:SHIELDS:READ', 'IOT:SHIELDS:CREATE', 'IOT:SHIELDS:UPDATE', 'IOT:SHIELDS:DELETE',
    'IOT:SENSOR:READ', 'IOT:SENSOR:CREATE',
    'IOT:ALERTS:READ', 'IOT:ALERTS:CREATE', 'IOT:ALERTS:UPDATE', 'IOT:ALERTS:DELETE',
    'IOT:ZONES:READ', 'IOT:ZONES:CREATE', 'IOT:ZONES:UPDATE', 'IOT:ZONES:DELETE',
    'IOT:ANALYTICS:READ',
  ],
  manager: [
    'EXPLOITATIONS:READ', 'EXPLOITATIONS:UPDATE', 'EXPLOITATIONS:EXPORT',
    'HERD:READ', 'HERD:VALIDATE', 'HERD:EXPORT',
    // ✅ Manager gets HEALTH:READ only (for reports, list)
    'HEALTH:READ',
    // Granular read-only
    'HEALTH_RECORD:READ',
    'TREATMENT:READ',
    'VACCINATION:READ',
    'INTERVENTION:READ',
    'HEALTH_REPORT:READ',
    'REPRODUCTION:READ', 'REPRODUCTION:EXPORT',
    'IOT:SHIELDS:READ',
    'IOT:SENSOR:READ',
    'IOT:ALERTS:READ',
    'IOT:ZONES:READ',
    'IOT:ANALYTICS:READ',
  ],
  eleveur: [
    'EXPLOITATIONS:READ', 'EXPLOITATIONS:UPDATE',
    'HERD:READ', 'HERD:CREATE', 'HERD:UPDATE', 'HERD:DELETE',
    // ❌ NO HEALTH:... permissions – only granular for vaccinations
    // 'HEALTH:READ' is NOT given to eleveur
    'HEALTH_RECORD:READ',
    'TREATMENT:READ',
    'VACCINATION:READ', 'VACCINATION:CREATE', 'VACCINATION:UPDATE', 'VACCINATION:DELETE',
    'INTERVENTION:READ',
    // 'HEALTH_REPORT:READ' - NOT given to eleveur
    'REPRODUCTION:READ', 'REPRODUCTION:CREATE', 'REPRODUCTION:UPDATE', 'REPRODUCTION:DELETE',
    'IOT:SHIELDS:READ', 'IOT:SHIELDS:CREATE', 'IOT:SHIELDS:UPDATE', 'IOT:SHIELDS:DELETE',
    'IOT:SENSOR:READ', 'IOT:SENSOR:CREATE',
    'IOT:ALERTS:READ', 'IOT:ALERTS:CREATE', 'IOT:ALERTS:UPDATE', 'IOT:ALERTS:DELETE',
    'IOT:ZONES:READ', 'IOT:ZONES:CREATE', 'IOT:ZONES:UPDATE', 'IOT:ZONES:DELETE',
    'IOT:ANALYTICS:READ',
  ],
  ouvrier: [
    'EXPLOITATIONS:READ',
    'HERD:READ',
    'HEALTH_RECORD:READ',
    'TREATMENT:READ',
    'VACCINATION:READ',
    'INTERVENTION:READ',
  ],
  veterinaire: [
    'EXPLOITATIONS:READ',
    'HERD:READ', 'HERD:UPDATE',
    // ✅ Vet gets old HEALTH permissions (full)
    'HEALTH:READ', 'HEALTH:CREATE', 'HEALTH:UPDATE', 'HEALTH:DELETE',
    // And granular ones too
    'HEALTH_RECORD:READ', 'HEALTH_RECORD:CREATE', 'HEALTH_RECORD:UPDATE', 'HEALTH_RECORD:DELETE',
    'TREATMENT:READ', 'TREATMENT:CREATE', 'TREATMENT:UPDATE', 'TREATMENT:DELETE', 'TREATMENT:ADMINISTER',
    'VACCINATION:READ', // read only for vaccinations (eleveur manages them, but vet can see)
    'INTERVENTION:READ', 'INTERVENTION:CREATE', 'INTERVENTION:UPDATE', 'INTERVENTION:DELETE',
    'HEALTH_REPORT:READ',
    'IOT:SHIELDS:READ',
    'IOT:SENSOR:READ',
    'IOT:ALERTS:READ',
    'IOT:ANALYTICS:READ',
  ],
  cooperative: [
    'EXPLOITATIONS:READ', 'EXPLOITATIONS:AGGREGATE',
    'HERD:READ', 'HERD:AGGREGATE',
    'HEALTH_RECORD:READ',
    'TREATMENT:READ',
    'VACCINATION:READ',
    'INTERVENTION:READ',
    'HEALTH_REPORT:READ',
  ],
};

export function hasPermission(roleName: string, module: string, action: string): boolean {
  const normalizedRole = roleName.toLowerCase();
  const perms = PERMISSIONS_MAP[normalizedRole] || [];
  return perms.includes(`${module}:${action}`);
}

export function canAccessModule(roleName: string, module: string): boolean {
  const normalizedRole = roleName.toLowerCase();
  const perms = PERMISSIONS_MAP[normalizedRole] || [];
  return perms.some(p => p.startsWith(`${module}:`));
}